### ISSUE TITLE
Segfault in test_read_fits_spec.py

### ISSUE THREAD

**Issue by nhmc** [linetools/linetools#11]
When running all tests via py.test, test_read_fits_spec.py causes a seg fault. Strangely this doesn't happen if the file is run by itself, only if all the tests are run at once.

**Comment by profxj** [comment]
Can you show me the precise line that you executed?

**Comment by nhmc** [comment]
Here is the output:

```
NCRIGHTON-MAC:linetools ncrighton$ ls
MANIFEST.in        ah_bootstrap.pyc   docs               licenses           setup.cfg
README.md          astropy_helpers    ez_setup.py        linetools          setup.py
ah_bootstrap.py    build              htmlcov            linetools.egg-info
NCRIGHTON-MAC:linetools ncrighton$ py.test linetools
====================================== test session starts =======================================
platform darwin -- Python 2.7.10 -- py-1.4.20 -- pytest-2.5.2

Running tests with Astropy version 1.0.2.
Running tests in linetools.

Platform: Darwin-13.4.0-x86_64-i386-64bit

Executable: /Users/ncrighton/anaconda/bin/python

Full Python Version: 
2.7.10 |Anaconda 2.0.1 (x86_64)| (default, May 28 2015, 17:04:42) 
[GCC 4.2.1 (Apple Inc. build 5577)]

encodings: sys: ascii, locale: UTF-8, filesystem: utf-8, unicode bits: 15
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.9.2
Scipy: 0.15.1
Matplotlib: 1.4.3
h5py: 2.3.0

collected 22 items 

linetools/lists/tests/test_init_linelist.py ..............
linetools/lists/tests/test_parse_lists.py ....
linetools/spectra/tests/test_read_fits_spec.py Segmentation fault: 11
NCRIGHTON-MAC:linetools ncrighton$
```

**Comment by profxj** [comment]
I have not reproduced the crash (and note that I have many more tests).
My Python is older but my pytest is newer..

wolverine.local> py.test linetools
============================= test session starts ==============================
platform darwin -- Python 2.7.9 -- py-1.4.25 -- pytest-2.6.3

Running tests with Astropy version 1.1.dev12774.
Running tests in linetools.

Platform: Darwin-13.4.0-x86_64-i386-64bit

Executable: /Users/xavier/anaconda/bin/python

Full Python Version:
2.7.9 |Anaconda 2.1.0 (x86_64)| (default, Dec 15 2014, 10:37:34)
[GCC 4.2.1 (Apple Inc. build 5577)]

encodings: sys: ascii, locale: UTF-8, filesystem: utf-8, unicode bits: 15
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.9.2
Scipy: 0.15.1
Matplotlib: 1.4.3
h5py: 2.3.1

collected 27 items

linetools/lists/tests/test_init_linelist.py ..............
linetools/lists/tests/test_parse_lists.py ....
linetools/lists/tests/test_use_linelist.py ....
linetools/spectra/tests/test_read_fits_spec.py .
linetools/tests/test_absline_anly.py ..
linetools/tests/test_init_absline.py ..

========================== 27 passed in 49.73 seconds ==========================
wolverine.local>

**Comment by nhmc** [comment]
Thanks. It turns out updating from Astropy 1.02 to 1.03 fixes the problem.
