### ISSUE TITLE
Make all attributes/methods of XSpectrum1D instance show up in dir()

### ISSUE THREAD

**Issue by nhmc** [linetools/linetools#129]
Currently the builtin method dir() only shows a small subset of all the methods on an XSpectrum1D instances. This means that you can't use tab completion in ipython to discover all the XSpectrum1D methods. The methods currently shown are:

``` python
In [1]: from linetools.spectra.xspectrum1d import XSpectrum1D
In [2]: wa = np.arange(10,20,1)
In [3]: s = XSpectrum1D.from_tuple((wa, np.ones_like(wa)))
In [4]: dir(s)
Out[4]: 
['_data',
 '_mask',
 '_meta',
 '_uncertainty',
 '_unit',
 '_wcs',
 '_wcs_attributes',
 'energy',
 'energy_unit',
 'filename',
 'frequency',
 'frequency_unit',
 'indexer',
 'wavelength',
 'wavelength_unit']
```

This might be caused Spectrum1D, which overloards `__dir__()`. I also tried overloading `__dir__()` in XSpectrum1D, but without any luck.

**Comment by profxj** [comment]
Far more painful then I expected, but I got it.

http://www.voidspace.org.uk/python/weblog/arch_d7_2011_05_21.shtml

**Comment by nhmc** [comment]
I agree this is better, but it would still be nice to get the dynamically-created attributes (e.g. wavelength, frequency) to show up. I'll leave this open for now.

**Comment by profxj** [comment]
They can be added ‘by-hand’ to the method.
Not sure how to add them dynamically.  ;)

> On Jan 17, 2016, at 8:44 PM, Neil Crighton <notifications@github.com> wrote:
> 
> I agree this is better, but it would still be nice to get the dynamically-created attributes (e.g. wavelength, frequency) to show up. I'll leave this open for now.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/linetools/linetools/issues/129#issuecomment-172424613>.
> 
> !DSPAM:826,569c6d9f1777155517411!

----------------------------------------------
J. Xavier Prochaska
UCO/Lick Observatory
1156 High St.
UC Santa Cruz
Santa Cruz, CA 95064

http://www.ucolick.org/~xavier/
http://imps.ucolick.org/
http://www.qpqsurvey.org/
http://k1dm3.ucolick.org/
http://www.ucolick.org/~xavier/IDL/index.html
https://github.com/pyigm/pyigm
https://github.com/linetools/linetools

831-459-2135 (Direct)
831-459-2991 (UCO/Lick Main)
831-459-5244 (Fax)

**Comment by nhmc** [comment]
Closing this now that we're no longer inheriting from Spectrum1D.
