### ISSUE TITLE
Unify code for plotting and GUI navigation

### ISSUE THREAD

**Issue by ntejos** [linetools/linetools#143]
Unify code for plotting and GUI navigation in order to avoid code duplication. I think we want something like:

- linetools.analysis.interactive_plot.py 

in the current linetools.guis.

**Comment by nhmc** [comment]
Agreed.

**Comment by profxj** [comment]
On it.

**Comment by ntejos** [comment]
Can we close this issue?

**Comment by nhmc** [comment]
Yes, please do.
