### ISSUE TITLE
XSpectrum1D: relative_vel()

### ISSUE THREAD

**Issue by ntejos** [linetools/linetools#145]
I feel that relative_vel() should not exist within XSpectrum1D. This seems to me more an object related to an absorption/emission line rather than the whole spectrum, but I think is general enough to be utils.py module somewhere. I came to this conclusion while revisiting the code for spectralline.py (I'm currently aiming at adding tests for it). It would also be nice to add extra capabilities, like using a relativistic approximation.

**Comment by nhmc** [comment]
linetools.utils currently has `v_from_z` and `z_from_v` functions. I would be happy with this code moving there too. Then `relative_vel` would be a wrapper calling the relevant code from utils.

**Comment by ntejos** [comment]
Sounds good to me.

**Comment by profxj** [comment]
@ntejos is this resolved?

**Comment by ntejos** [comment]
Not sure. I still think relative_vel() method should not belong to the
XSpectrum1D class, but maybe you use it for plotting purpuses?

**Comment by profxj** [comment]
ok, will move the method but keep this wrapper

**Comment by profxj** [comment]
Addressed by PR #306
