### ISSUE TITLE
xspec gui visual guides for measuring EW and AOD 

### ISSUE THREAD

**Issue by nhmc** [linetools/linetools#156]
When you use 'E' or 'N' to measure the equivalent width or N in lt_xspec, it shows two green dots joined by a line. This suggests that the vertical position of the dots is taken into account when calculating N/EW, which is not the case. The visual guides should be tweaked to fixed this. Maybe just make them vertical lines, instead of dots?

**Comment by ntejos** [comment]
It seems that  lt_xspec does uses the position of the cursor given by the green marks for establishing the continuum level. Thus, having those marks is not misleading at all, but necessary in the current implementation. Will close the issue accordingly.
