### ISSUE TITLE
guis.utils.read_spec should be using spectra.io.readspec

### ISSUE THREAD

**Issue by nhmc** [linetools/linetools#157]
Currently it doesn't read UVES_popler spectra correctly, for example.

**Comment by profxj** [comment]
Good one! :)

On it.

X


> On Jan 19, 2016, at 5:16 PM, Neil Crighton <notifications@github.com> wrote:
> 
> Currently it doesn't read UVES_popler spectra correctly, for example.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/linetools/linetools/issues/157>.
> 
> !DSPAM:826,569edfef209871030819716!

----------------------------------------------
J. Xavier Prochaska
UCO/Lick Observatory
1156 High St.
UC Santa Cruz
Santa Cruz, CA 95064

http://www.ucolick.org/~xavier/
http://imps.ucolick.org/
http://www.qpqsurvey.org/
http://k1dm3.ucolick.org/
http://www.ucolick.org/~xavier/IDL/index.html
https://github.com/pyigm/pyigm
https://github.com/linetools/linetools

831-459-2135 (Direct)
831-459-2991 (UCO/Lick Main)
831-459-5244 (Fax)

**Comment by nhmc** [comment]
Closing, because this got fixed at some point.
