### ISSUE TITLE
Change subset_lines to return a new LineList instance

### ISSUE THREAD

**Issue by nhmc** [linetools/linetools#158]
I think it would be better to change LineList.subset_lines so that it returns a new LineList instance, instead of modifying the original linelist.  What do you think @ntejos?

**Comment by ntejos** [comment]
I've been thinking about this... I would originally have preferred
for LineList.subset_lines to return a new LineList instance as you said,
but @profxj had it this way for a reason I believe... Should we reconsider
changing this?

---Nicolas

**Comment by nhmc** [comment]
@profxj what do you think?

**Comment by profxj** [comment]
If @ntejos is right, we should probably remember why.
I fear I can't..

Feel free to do it and I'll deal.

**Comment by ntejos** [comment]
I think it was the case to avoid reloading all the tables with transitions every time. Now with the `CACHE` that may not longer be an issue and we should follow Neil's suggestion (assuming there was nothing else about it). I will try to implement it tomorrow self consistently within linetools, but this will likely also affect other packages like pyigm and xastropy. Anyways, those should be easy fixes.

**Comment by nhmc** [comment]
Ok, thanks.

**Comment by nhmc** [comment]
Closed by #163.
