### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by profxj** [linetools/linetools#180]
Should we add this file to aid in installation?

[https://pip.readthedocs.org/en/1.1/requirements.html](url)

**Comment by nhmc** [comment]
Currently we aren't using the pip infrastructure to install dependencies, we ask the user to make sure all the dependencies are present. I did this because this follows other affiliated packages (e.g. photutils). But I guess it can't hurt to add the requirements file...

**Comment by profxj** [comment]
closing
