### ISSUE TITLE
v0.2

### ISSUE THREAD

**Issue by profxj** [linetools/linetools#185]
Now that we have launched v0.1, might as well
dream about v0.2.  ;)

Add to this wish list as you wish:
1. LineList for AGN
2. IGMGuesses
3. Simple emission-line measurements
4. Redshift fitting (or at least hooks to it)
5. 2D spectral line codes?
6. Yet more spectral line data

**Comment by nhmc** [comment]
I made a v0.2 milestone with a (arbitrary) deadline of 30 April :)

It would also be nice to have:

 - automatic feature-finder (absorption + emission)
 - Velocity plots callable from xspec
 - a vpfit (and Alis?) parameter file parser, to display fits.

**Comment by profxj** [comment]
Returning to this

1. I can do this
1. This is in pyigm now
1. Nothing done here yet
1. Same
1. Nothing
1. Some progress and I have a visitor who might help me with more

As for @nhmc 's list:

1. Nothing automatic
1. I thought we could do this already. Will add now
1. This sounds easy.  @ntejos , is this implemented?

**Comment by ntejos** [comment]
There is progress on Neil's third point, but current implementation is done at the `AbsComponent` level. Because the user may have preferences on how to tie different components it is not obvious to me the best way to implement this at an upper level (say, `AbsSystem`).

**Comment by profxj** [comment]
@nhmc , @ntejos please comment on:

1.  When to make a second release
2.  Remind me how to make this a formal request as an affiliated astropy package

**Comment by nhmc** [comment]
1. I suggest we do a new release as soon as possible.
2. #232 describes how to request status as an astropy affiliated package. The first step is to send an email to astropy-dev.

**Comment by profxj** [comment]
Email sent with an initial inquiry.  

Let's have v0.2 out on August 1.

**Comment by ntejos** [comment]
Sounds good to me.

**Comment by profxj** [comment]
it is my intent to clear PR#305, PR#309 and then tag as v02
and then submit to astropy.

@ntejos please confirm you are ok with this.
@nhmc  you too if you are listening.  :)

**Comment by ntejos** [comment]
Sounds good to me.

**Comment by profxj** [comment]
Released.
