### ISSUE TITLE
astropy affiliated package

### ISSUE THREAD

**Issue by profxj** [linetools/linetools#232]
I'd like this package to get reviewed and affiliated by astropy.

What does that take?

**Comment by nhmc** [comment]
http://www.astropy.org/affiliated/#affiliated-instructions

I think we broadly address those criteria (although there is room for improvement in the documentation).

**Comment by profxj** [comment]
Shall we submit?  Or make a goal to submit
on some date?


> On Jun 20, 2016, at 11:32 PM, Neil Crighton <notifications@github.com> wrote:
> 
> http://www.astropy.org/affiliated/#affiliated-instructions <http://www.astropy.org/affiliated/#affiliated-instructions>
> I think we broadly address those criteria (although there is room for improvement in the documentation).
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/linetools/linetools/issues/232#issuecomment-227352232>, or mute the thread <https://github.com/notifications/unsubscribe/AD0BjfdErcRwDRlZ-N4lscaIVdJjk_PVks5qN4VwgaJpZM4I5sDV>.
> 
> !DSPAM:826,5768df74250908342118!

----------------------------------------------
J. Xavier Prochaska
UCO/Lick Observatory
1156 High St.
UC Santa Cruz
Santa Cruz, CA 95064

http://www.ucolick.org/~xavier/
http://imps.ucolick.org/
http://www.qpqsurvey.org/
http://k1dm3.ucolick.org/
http://www.ucolick.org/~xavier/IDL/index.html
https://github.com/pyigm/pyigm
https://github.com/linetools/linetools

831-459-2135 (Direct)
831-459-2991 (UCO/Lick Main)
831-459-5244 (Fax)

**Comment by profxj** [comment]
Request submitted.  Closing
