### ISSUE TITLE
Replace Barak routines in spectra/convolve.py with Astropy equivalents

### ISSUE THREAD

**Issue by nhmc** [linetools/linetools#28]

**Comment by ntejos** [comment]
Done. I still think we should deprecate spectra/convolve.py and use astropy.convolution equivalents directly.

**Comment by nhmc** [comment]
Feel free to open an issue about this. But I think we may still want to include some of our own convolution stuff (like convolving in constant-velocity space) even if we remove `convolve_psf` and `convolve_window`.

**Comment by ntejos** [comment]
What you say makes sense, so let's leave it as it is.
