### ISSUE TITLE
Modify io.py to ingest continua generated by linetools

### ISSUE THREAD

**Issue by profxj** [linetools/linetools#290]
Masked pixels are causing issues here.

**Comment by lwymarie** [comment]
Here is my summary of the two issues. 

First, the line xspec1d.data['co'] = fits.getdata(co_filename) unintentionally resets the mask on the continuum array, which is supposed to be handled in the XSpectrum1D class definition only. 

Second, the code only searches for continuum files ending with _c.fits, so _c.fits.gz files are overlooked.

**Comment by profxj** [comment]
@lwymarie is this issue closed?

**Comment by lwymarie** [comment]
Yes. Please close it.
