### ISSUE TITLE
readspec: issue with parse_linetools_spectrum_format()

### ISSUE THREAD

**Issue by ntejos** [linetools/linetools#300]
There is an issue with `parse_linetools_spectrum_format()` when trying to read a fits table with continuum (generated by lt_continuumfit)::

> lt_xspec 3C273_cont.fits

```

/home/ntejos/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py:872: UserWarning:  axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
   warnings.warn(self.msg_depr % (key, alt_key))
Traceback (most recent call last):
  File "/home/ntejos/anaconda/bin/lt_xspec", line 9, in <module>
    load_entry_point('linetools', 'console_scripts', 'lt_xspec')()
  File "/home/ntejos/python/linetools/linetools/scripts/lt_xspec.py", line 77, in main
    rsp_kwargs=rsp_kwargs, air=pargs.air)
  File "/home/ntejos/python/linetools/linetools/guis/xspecgui.py", line 60, in __init__
    rsp_kwargs=rsp_kwargs, **kwargs)
  File "/home/ntejos/python/linetools/linetools/guis/spec_widgets.py", line 71, in __init__
    rsp_kwargs=rsp_kwargs)
  File "/home/ntejos/python/linetools/linetools/guis/utils.py", line 207, in read_spec
    spec = lsx.XSpectrum1D.from_file(spec_fil, exten=exten, **kwargs['rsp_kwargs'])
  File "/home/ntejos/python/linetools/linetools/spectra/xspectrum1d.py", line 67, in from_file
    slf = tio.readspec(ifile, **kwargs)
  File "/home/ntejos/python/linetools/linetools/spectra/io.py", line 127, in readspec
    xspec1d = parse_linetools_spectrum_format(hdulist)
  File "/home/ntejos/python/linetools/linetools/spectra/io.py", line 617, in parse_linetools_spectrum_format
    xspec1d.meta.update(json.loads(hdulist[0].header['METADATA']))
  File "/home/ntejos/anaconda/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/home/ntejos/anaconda/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 10798 - line 1 column 10801 (char 10797 - 10800)
```

It seems that the json.decoder does not like the format of the metadata when including the continuum points generated by linetools in its current implementation (hence `json.loads` fails). Note that we are currently storing the continuum points as an array of [x,y] arrays using the keyword "contpoints" in the metadata, e.g. 

> "contpoints": [ [1135.441775070131, 3.582729279171351e-13], [1137.1672833723442, 3.8706199775988086e-13], [1139.4259170966695, 4.046899534232429e-13], .... , ]

My thoughts are that these should be anyways interpreted as ascii characters, so not sure what is going on...

**Comment by ntejos** [comment]
Update:

Here is the full string that is causing trouble:
`
'{"airvac": "vac", "headers": ["SIMPLE  =                    T / conforms to FITS standard                      BITPIX  =                  -32 / array data type                                NAXIS   =                    1 / number of array dimensions                     NAXIS1  =                11182                                                  EXTEND  =                    T                                                  EXTNAME = \'FLUX    \'extension name                                 CREATOR = \'JT      \'                                                            HIERARCH TIMESTAMP = \'2016-03-07 12:13:25.431936\'                               LEGACY  = \'HST-50MP\'                                                            METADATA= \'{\\"airvac\\": \\"vac\\", \\"headers\\": [\\"SIMPLE  =                    T / &\'   CONTINUE  \'conforms to FITS standard                      BITPIX  =           &\'CONTINUE  \'         8 / array data type                                NAXIS  &\'CONTINUE  \' =                    0 / number of array dimensions               &\'CONTINUE  \'      EXTEND  =                    T                               &\'CONTINUE  \'                   CREATOR = \'JT      \'                          &\'CONTINUE  \'                                  HIERARCH TIMESTAMP = &\'            CONTINUE  \'\'2016-03-07 12:13:25.431936\'                               &\'      CONTINUE  \'LEGACY  = \'HST-50MP\'                                             &\'CONTINUE  \'               END                                                 &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                                   &\'CONTINUE  \'                                                         \\"]}\'        NSPEC   =                    1                                                  NPIX    =                11182                                                  UNITS   = \'{\\"flux\\": \\"dimensionless_unit\\", \\"wave\\": \\"Angstrom\\"}\'                  END                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "], "contpoints": [[1135.441775070131, 3.582729279171351e-13], [1137.1672833723442, 3.8706199775988086e-13], [1139.4259170966695, 4.046899534232429e-13], [1141.8996587947402, 4.107775859914231e-13], [1144.3303788980618, 4.136365237685693e-13], [1146.4599478381401, 4.146635021028827e-13], [1150.6039811601356, 3.82402792945937e-13], [1153.7209174919117, 3.826329100917661e-13], [1156.6248751374728, 3.7820382242365145e-13], [1158.2000303711914, 3.720031823816611e-13], [1159.8418148848334, 3.649165594193072e-13], [1163.2640631785616, 3.6854308667344515e-13], [1165.4346222022104, 3.671311032533646e-13], [1168.1664934687753, 3.6934564708742194e-13], [1170.46814878785, 3.75989278589594e-13], [1173.177755787354, 3.8355944277785156e-13], [1178.456161600673, 4.035609465959794e-13], [1180.9881780043584, 4.2644878834213607e-13], [1183.7943006460575, 4.512141186374378e-13], [1186.0522108117289, 4.766331101503651e-13], [1188.3887940805685, 4.933601017946345e-13], [1191.4317130189004, 5.27062660009292e-13], [1195.6282529369657, 5.31809331946547e-13], [1198.1019946350364, 5.213293120127232e-13], [1203.7763256375256, 4.4695350935944345e-13], [1208.840358444896, 3.49004950373627e-13], [1211.3723748485813, 2.6918254902153255e-13], [1212.7099771320777, 1.754886541965375e-13], [1214.0436465692985, 2.277979230367625e-14], [1217.4208417570992, 3.6254103647164015e-14], [1218.968424059637, 1.8660780928304865e-13], [1220.636705964591, 2.673792262224346e-13], [1221.5004404633223, 2.855466945498377e-13], [1223.1749800547852, 3.139535965858041e-13], [1226.0262362467788, 3.3335958423720795e-13], [1229.096489674378, 3.468822993603349e-13], [1231.6285060780633, 3.4758305002561045e-13], [1233.2968857593692, 3.522423238505601e-13], [1236.6925388854338, 3.5129565272365437e-13], [1241.7565716928043, 3.5746100780302645e-13], [1244.4476765410623, 3.5323420243387056e-13], [1246.7647959955605, 3.5082497312347157e-13], [1249.35262090386, 3.42645454110696e-13], [1253.067459626297, 3.3724078176748875e-13], [1254.4166537112303, 3.3848542458497777e-13], [1256.9486701149156, 3.3124374011934965e-13], [1262.012702922286, 3.206407886696714e-13], [1265.0203098210045, 3.195917501729339e-13], [1268.396331692585, 3.1174790989282957e-13], [1271.4132953574804, 3.1751559253396965e-13], [1275.9923809036404, 3.1460021544923115e-13], [1279.21015174999, 3.1317406267103034e-13], [1282.268834151768, 3.0932046130004134e-13], [1285.0126893417687, 3.1673944461653233e-13], [1287.3328669591385, 3.147667673383814e-13], [1289.8648833628238, 3.214162334723436e-13], [1292.5440749680295, 3.2559718917664637e-13], [1294.928916170194, 3.259582274234285e-13], [1297.4609325738793, 3.2032189400954536e-13], [1300.4073469482878, 3.2559718917664637e-13], [1303.2037506069764, 3.1977539288122523e-13], [1306.402952918734, 3.217309793402351e-13], [1310.2281014896282, 3.217159916463656e-13], [1312.6530309959908, 3.150737727360479e-13], [1315.185047399676, 3.146801395847998e-13], [1317.7170638033613, 3.129340590910662e-13], [1320.476899097346, 3.0946146445544746e-13], [1323.8081108769902, 3.0785063883974306e-13], [1327.6349654704688, 3.0390406961272517e-13], [1330.3771458217875, 3.022942139663254e-13], [1332.834882309148, 3.0462898760833416e-13], [1337.7425624113862, 3.0813180029038285e-13], [1343.0372278402137, 3.0568459054665896e-13], [1345.569244243899, 3.101341340856767e-13], [1350.1661234350443, 3.178347941160849e-13], [1353.1652934549547, 3.246464068612136e-13], [1357.1904743176963, 3.391813805326292e-13], [1360.3955831265007, 3.469437755931908e-13], [1363.2933590696957, 3.432979700997751e-13], [1365.825375473381, 3.444006961127871e-13], [1367.9361931461412, 3.4500317682805033e-13], [1371.368240867247, 3.488843743583311e-13], [1373.4214246844367, 3.6228133862865226e-13], [1375.953441088122, 3.6690155037419347e-13], [1378.74644436671, 3.896369484262794e-13], [1381.0174738954925, 4.0396635689332605e-13], [1383.5494902991777, 4.2427025040299666e-13], [1386.081506702863, 4.422244905336048e-13], [1388.6962636922974, 4.730826953273164e-13], [1391.1455395102334, 5.05971024626628e-13], [1395.742125372324, 6.283305965385479e-13], [1398.8084895380628, 7.408853249166907e-13], [1401.2392096413844, 8.650836458856759e-13], [1403.8056215286595, 1.0445732623257906e-12], [1406.3376379323447, 1.147627782735472e-12], [1408.86965433603, 9.945570842578855e-13], [1413.9336871434004, 7.04771934171769e-13], [1416.4657035470857, 5.92545218620899e-13], [1418.997719950771, 5.264162586740562e-13], [1422.0519816411081, 4.880777856527962e-13], [1424.4582177405537, 4.639149849862412e-13], [1426.710144812562, 4.599314007431505e-13], [1431.4210094375835, 4.641251368423562e-13], [1434.1898183728822, 4.582108987929612e-13], [1438.8540654703513, 4.4315645634632805e-13], [1444.3178839876232, 3.911849426594308e-13], [1447.1045318033514, 3.655723385110242e-13], [1451.913933198679, 3.523515030093294e-13], [1454.4459496023642, 3.43475453995411e-13], [1462.04199881342, 3.255984891425978e-13], [1469.6380480244757, 3.068600331221457e-13]]}\' /'`

I first looked at characters 10798,10801 and also 10797 - 10800. They did not look suspicious at all. Thus, I tested by editing the ending part, i.e. deleting the  last 3 so the string ends with`]]}'` and that seemed to work. Of course, this is not a pretty solution and we should track the bug down properly, probably related on how the contpoints are stored in the metadata. I will submit a patch PR in the meantime...

**Comment by profxj** [comment]
@ntejos is this closed?

**Comment by ntejos** [comment]
Is solved by my ugly patch, but I think it should be corrected at the level where the metadata is written by the continuum fit. Could you have a look?

**Comment by profxj** [comment]
No, I'm not willing to dig into that code anytime soon.  It's Neil's and a bit hard for me to handle.
Or am I mistaken and is it in XSpectrum1D?

**Comment by ntejos** [comment]
Closing because this troublesome metadata is no longer being stored.
