### ISSUE TITLE
Preferred Citation

### ISSUE THREAD

**Issue by augustfly** [linetools/linetools#323]
hi,

I am a data editor/scientist for ApJ/AJ. Your linetools code has been mentioned in an accepted manuscript, and I am investigating a preferred citation method for your code. 

Do you have a preferred citation method that you could provide me and list in your project README? 

In addition to a software paper, we prefer some kind of archival copy DOI citation minted by the Github=>Zenodo workflow (<https://guides.github.com/activities/citable-code/>). I'm not trying to make busy work for you, but would really like to see this mention upgraded to a formal citation in this manuscript. 

thanks

**Comment by profxj** [comment]
I have (I think) added a DOI with Zenodo on our v0.2

I fear there is no software paper on the repository.  And
probably not one forthcoming..

**Comment by augustfly** [comment]
Yes, I see it. Thanks for doing this. I'll update the corresponding manuscript.

You should see this Zenodo entry indexed in ADS sometime in 2017.
