### ISSUE TITLE
Implement automatic redshift assignment + template matching for XSpectrum1D

### ISSUE THREAD

**Issue by ntejos** [linetools/linetools#327]
As stated.

**Comment by profxj** [comment]
I'm not sure linetools is the place for this.

There are sophisticated tools being developed (or already developed)
for such analysis.  e.g.  RedMonster

**Comment by ntejos** [comment]
You are right. I was having a look at redmonster repository, but could not find documentation to run it. I guess we can at least have a wrapper to those? Although it would add extra dependencies which is not ideal. Will close the Issue for now.
