### ISSUE TITLE
Deal with bad pixels in rebinning error spectrum 

### ISSUE THREAD

**Issue by lwymarie** [linetools/linetools#334]
Line 282 of spectra/utils.py selects bad pixels as those with variance <= 0. 
But negative sigma values would give positive sigma^2.

**Comment by lwymarie** [comment]
In the latest version, it becomes line 313. This issue has not been addressed.

**Comment by profxj** [comment]
Please generate a simple test which exhibits the issue and send to me.

**Comment by lwymarie** [comment]
It's taken care of in the latest version. Sorry about that. I'll close.
