### ISSUE TITLE
xspectrum1d write_to_fits doesn't write the right data arrays

### ISSUE THREAD

**Issue by yzhenggit** [linetools/linetools#389]
was trying to do: 

import linetools.spectra.xspectrum1d as lsx
specname = 'SBS1122+594_coadd_FUVM_final_all.fits.gz'  ## a coadded QSO from HSLA
spec = lsx.XSpectrum1D.from_file(specname)
spec.write_to_fits('test.fits') 

Two issues: 
=============
First, astropy.table.Table cannot read this test.fits table, I got error like: 
ValueError                                Traceback (most recent call last)
<ipython-input-9-eff30362679b> in <module>()
----> 1 a = Table.read('/Users/Yong/Desktop/test.fits', format='fits')

/Users/Yong/anaconda3/lib/python3.5/site-packages/astropy/table/table.py in read(cls, *args, **kwargs)
   2330         passed through to the underlying data reader (e.g. `~astropy.io.ascii.read`).
   2331         """
-> 2332         return io_registry.read(cls, *args, **kwargs)
   2333 
   2334     def write(self, *args, **kwargs):

/Users/Yong/anaconda3/lib/python3.5/site-packages/astropy/io/registry.py in read(cls, *args, **kwargs)
    349 
    350         reader = get_reader(format, cls)
--> 351         data = reader(*args, **kwargs)
    352 
    353         if not isinstance(data, cls):

/Users/Yong/anaconda3/lib/python3.5/site-packages/astropy/io/fits/connect.py in read_table_fits(input, hdu)
    136 
    137         try:
--> 138             return read_table_fits(hdulist, hdu=hdu)
    139         finally:
    140             hdulist.close()

/Users/Yong/anaconda3/lib/python3.5/site-packages/astropy/io/fits/connect.py in read_table_fits(input, hdu)
    125             table = tables[first(tables)]
    126         else:
--> 127             raise ValueError("No table found")
    128 
    129     elif isinstance(input, (TableHDU, BinTableHDU, GroupsHDU)):

ValueError: No table found
================================
Second, when using astropy.io.fits, I found that only one array (it's the flux values I think) was written. 

import astropy.io.fits as fits
a = fits.getdata('test.fits')

Then a.shape, np.mean(a) gives ((76958,), 4.5521139e-15)

**Comment by profxj** [comment]
can you stage the HSLA spectrum somewhere (i.e. paste
the link into this Issue)  ?

**Comment by yzhenggit** [comment]
https://www.dropbox.com/s/jwx786tjvzmva4d/SBS1122%2B594_coadd_FUVM_final_all.fits.gz?dl=0

**Comment by profxj** [comment]
I had no issue here. Not sure what the
source of your problem is.  See this Notebook:

https://www.dropbox.com/s/dy3yxddfylxu9z7/Fiddling.ipynb?dl=0

**Comment by yzhenggit** [comment]
Yes, up to the 'write_to_fits' line is fine as your notebook. 

ok, so the new table tmp.fits can be read by readspec again without any loss. I thought it's in a format that astropy.table.Table can understand, but it seems not. Not an issue though.

**Comment by profxj** [comment]
you can write as Binary FITS table too
and I suspect astropy would be fine with that.

**Comment by yzhenggit** [comment]
Nope, it's not happy that way either.
