### ISSUE TITLE
7 unit tests fail (Python 2.7)

### ISSUE THREAD

**Issue by bomilvangjensen** [linetools/linetools#394]
I made a fresh anaconda Python 2.7 environment, installed future and ginga, installed linetools and ran the unit tests, of which these 7 test failed:

test_lsf_COS
test_lsf_STIS
test_interpolate_to_wv0
test_interpolate_to_wv_array
test_get_lsf
test_all_lp
test_interpolate_to_wv0_wv0shortlong

all with error:

E       IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

Full STDOUT/STDERR should be here:
[linetools_unittests_output.txt](https://github.com/linetools/linetools/files/1047780/linetools_unittests_output.txt)

**Comment by profxj** [comment]
I see no troubles with 2.7 on Travis:

https://travis-ci.org/linetools/linetools/builds/238424009

**Comment by bomilvangjensen** [comment]
My error is in linetools/spectra/lsf.py in this code bit:

        n_half = (n_pix - 1) / 2
        mid_value = relpix[n_half]

n_pix is an integer (e.g. 201), but using the future division, n_half is a float, (e.g. 100.0) and I am not so surprised I cannot use that as an index. But I am surprised that Travis can, apparently with the same Python version as me, Python 2.7.13.

**Comment by profxj** [comment]
Hmm..  I think you have something.  
Best would be to:

- Fork the code (or I can give you write permission to the Repo if you wish)
- Write a new test hitting that line of code
- Test via Travis

**Comment by bomilvangjensen** [comment]
Thanks, but I'm not sure I have the full technical skills to do that. I can say that just changing the / to // (i.e. integer division) in that line makes me pass all unit tests. So I would suggest that change be implemented.

I use Numpy: 1.12.1 whereas Travis uses Numpy: 1.11.3, so therein probably lies
the difference to the handling of using e.g. 100.0 as an index.

**Comment by ntejos** [comment]
Maybe I can just add `n_half=int(n_half)`?
