### ISSUE TITLE
lt_xspec: 'D' and 'R' keys without a QSO continuum

### ISSUE THREAD

**Issue by sstawins** [linetools/linetools#424]
Hello,
The 'D' and 'R' keys in lt_xspec don't work unless there is also a plotted continuum for the QSO. Is there a way to use these keys without a QSO continuum? 
Thank you

**Comment by profxj** [comment]
I am not finding this to be true.  
Just tried on a fluxed QSO spectrum without a continuum.
So something else is going on.

Am closing this issue but please reopen a new one with 
a more precise description of the problem. Thanks
