### ISSUE TITLE
Using 'D' and 'R' keys when continuum = 0

### ISSUE THREAD

**Issue by khrrubin** [linetools/linetools#429]
Hello,

We've come across some QSOs in QPQ whose continua are set to zero.  In these cases, this incorrect continuum appears automatically when using xspectrum1d.plot, making the 'D' and 'R' keys for inserting DLAs or SLLSs ineffective.  Some code which should hopefully recreate the problem is below.  Is there a way to avoid plotting the continuum in these cases?

Thanks so much,
Kate

import os
from specdb.specdb import IgmSpec
from enigma.qpq import qpq_query as qpqq

qpq_file = os.getenv('QSO_PAIRS') + '/qpq_oir_spec.hdf5'
qpq = IgmSpec(db_file=qpq_file, skip_test=True)
qdict = dict(GROUP_ID=4)

spec, meta = qpq.spectra_from_coord('130756.73+042215.5', query_dict=qdict)
spec.plot(xspec = True,co=False)

**Comment by profxj** [comment]
Try turning 'off' the continuum, i.e.

```
spec.is_co_set = False
```

**Comment by khrrubin** [comment]
If I try 

spec.co_is_set = False

I get 

AttributeError: can't set attribute

**Comment by profxj** [comment]
Ok, needed to a different kludge.  Note that this
will become obsolete when we finally migrate away
from XSpectrum1D (to Spectrum1D in astropy).

Try something like this:

```
import numpy as np
import os
from specdb.specdb import IgmSpec

qpq_file = os.getenv('SPECDB') + '/qpq_oir_spec_v2.hdf5'
qpq = IgmSpec(db_file=qpq_file, skip_test=True)
qdict = dict(GROUP_ID=4)

spec, meta = qpq.spectra_from_coord('130756.73+042215.5', query_dict=qdict)

spec.data['co'][spec.select] = np.nan
print(spec.co_is_set)
```

Note that you'll want to grab the latest QPQ file
and it should be in a folder named SPECDB [these
are not linetools things of course]

**Comment by khrrubin** [comment]
Ok, great, this works!  Thanks!
