### ISSUE TITLE
Enforce sig_logN and sig_N be two element arrays

### ISSUE THREAD

**Issue by profxj** [linetools/linetools#450]
Presently, we have a mix of float and two element arrays (the 
latter handle asymmetric error).  This occasionally causes
trouble.  Am therefore inclined to head toward a framework
where the error is always 2 elements (and often the same 
value for each).

What say @jnburchett and @ntejos ?

**Comment by ntejos** [comment]
In principle fine, but would be nice to integrate consistently logN upper
limits into the preferred solution.

--
Nicolas Tejos, Ph.D.
Instituto de Física
Pontificia Universidad Católica de Valparaíso
Valparaíso, Chile
http://www.fis.ucv.cl/ntejos

**Comment by profxj** [comment]
Done.
