### ISSUE TITLE
problems with    linetools/spectra/io.py  and  voigt_from_abslines

### ISSUE THREAD

**Issue by fmannucci** [linetools/linetools#464]
Hi,
I'm trying to use linetools to fit voigt profiles to a spectrum.  To start I'm following the example Voigt_examples.ipynb:

> abslin = AbsLine(1215.670*u.AA)
> abslin.attrib['N'] = 10**14./u.cm**2  # log N
> abslin.attrib['b'] = 25.*u.km/u.s
> abslin.attrib['z'] = 2.0
> abslin.analy['spec'] = lsio.readspec('UM184_nF.fits')

where I have put UM814_nF.fits in the local directory

I get the error:

  File "<ipython-input-17-e4d7a10a112f>", line 5, in <module>
    abslin.analy['spec'] = lsio.readspec('UM184_nF.fits')

  File "/Users/filippo/anaconda2/envs/AstroPY2/lib/python2.7/site-packages/linetools/spectra/io.py", line 259, in readspec
    if sig is not None:

UnboundLocalError: local variable 'sig' referenced before assignment

Also, when using voig_from_absline (after the commands above) I get an error:

> wave = np.arange(1000.,5500.,0.3) * u.AA
> v=voigt_from_abslines(wave, abslin)

 File "<ipython-input-20-aed617a18d35>", line 86, in voigt_from_abslines
    iline.z, iline.attrib['b'].to('cm/s').value,

AttributeError: 'AbsLine' object has no attribute 'z'

Can you help?
thanks

**Comment by profxj** [comment]
Indeed, that Notebook was out-of-date.

Now updated in PR #474

**Comment by profxj** [comment]
Short answer is:

set redshift with

absline.setz(2.)
