### ISSUE TITLE
Interactive continuum fitting example attribute error

### ISSUE THREAD

**Issue by fcashman** [linetools/linetools#468]
I working through the Jupyter notebook and on the fourth input received the following error:
AttributeError: 'XSpectrum1D' object has no attribute 'dispersion'

The first three executed with no problem. Is this error on my end? Attached a screenshot of the input/output box. Thanks.

![continuum_error](https://user-images.githubusercontent.com/33284550/37915003-80124af4-30e6-11e8-8e10-e323d926f5bc.png)

**Comment by profxj** [comment]
Nope, not your fault.

The Notebook is out-of-date on this point.
Replace "dispersion" with "wavelength".

Will update before long.

**Comment by profxj** [comment]
I've decided that running the continuum fitting as in the
Notebook is a non-optimal approach.  Best to use just
the lt_continuumfit script from the command line.

Have removed this Notebook in PR #474
