### ISSUE TITLE
issue on opening spectrum file 

### ISSUE THREAD

**Issue by mc24tu** [linetools/linetools#496]
Whatever method I use to open the fits file of my spectrum, I get always the same problem. For example, by typing "lt_xspec filename.fits" I get the following message: 

`/spectra_analysis/RGS/xspecgui/linetools/linetools/spectra/io.py:538: UserWarning: No error tag found. Searched for these tags:
[u'ERROR', u'ERR', u'SIGMA_FLUX', u'ERR_FLUX', u'ENORM', u'FLAM_SIG', u'SIGMA_UP', u'ERRSTIS', u'FLUXERR', u'SIGMA', u'sigma', u'sigma_flux', u'er', u'err', u'error', u'sig', u'fluxerror', u'FLUX_ERROR', u'flux_error', u'IVAR', u'IVAR_OPT', u'ivar', u'FLUX_IVAR', u'VAR', u'var']
  warnings.warn('No error tag found. Searched for these tags:\n'+ str(sig_tags + ivar_tags + var_tags))
Traceback (most recent call last):
  File "/anaconda2/bin/lt_xspec", line 11, in <module>
    load_entry_point('linetools', 'console_scripts', 'lt_xspec')()
  File "/spectra_analysis/RGS/xspecgui/linetools/linetools/scripts/lt_xspec.py", line 91, in main
    screen_scale=scale)
  File "/spectra_analysis/RGS/xspecgui/linetools/linetools/guis/xspecgui.py", line 121, in __init__
    rsp_kwargs=rsp_kwargs, **kwargs)
  File "/spectra_analysis/RGS/xspecgui/linetools/linetools/guis/spec_widgets.py", line 154, in __init__
    rsp_kwargs=rsp_kwargs)
  File "/spectra_analysis/RGS/xspecgui/linetools/linetools/guis/utils.py", line 211, in read_spec
    spec = lsx.XSpectrum1D.from_file(spec_fil, exten=exten, **kwargs['rsp_kwargs'])
  File "/spectra_analysis/RGS/xspecgui/linetools/linetools/spectra/xspectrum1d.py", line 66, in from_file
    slf = tio.readspec(ifile, **kwargs)
  File "/spectra_analysis/RGS/xspecgui/linetools/linetools/spectra/io.py", line 116, in readspec
    xspec1d = parse_FITS_binary_table(hdulist, exten=exten, **kwargs)
  File "/spectra_analysis/RGS/xspecgui/linetools/linetools/spectra/io.py", line 556, in parse_FITS_binary_table
    wv_unit = get_wave_unit(wave_tag, hdulist, idx=exten)
  File "/spectra_analysis/RGS/xspecgui/linetools/linetools/spectra/io.py", line 296, in get_wave_unit
    hidx = values.index(tag)
ValueError: u'NONE' is not in list`

The same fits can be opened without any problems on xspec and it was obtained with the usual SAS threads for RGS analysis. So I am wondering if for linetools the spectra should have a particular header... Someone has some ideas? Thanks.

**Comment by profxj** [comment]
1.  Is the spectrum written as a binary FITS table?
2.  If so, can you provide its list of tags (keys)?

Or, better, stage the file somewhere and provide a link to it.

**Comment by mc24tu** [comment]
Yes the file is a binary fits table. 
```
>hdul = fits.open('o1spec.fits')
> hdul.info()
Filename: o1spec.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      11   ()      
  1  SPECTRUM      1 BinTableHDU     50   3600R x 5C   [I, J, I, E, E]   
> list(hdul[1].header.keys())
['XTENSION', 'BITPIX', 'NAXIS', 'NAXIS1', 'NAXIS2', 'PCOUNT', 'GCOUNT', 'TFIELDS', 'TTYPE1', 'TFORM1', 'TTYPE2', 'TFORM2', 'TUNIT2', 'TTYPE3', 'TFORM3', 'TTYPE4', 'TFORM4', 'TTYPE5', 'TFORM5', 'EXTNAME', 'TELESCOP', 'INSTRUME', 'FILTER', 'HDUCLASS', 'HDUCLAS1', 'HDUCLAS2', 'HDUCLAS3', 'HDUVERS', 'POISSERR', 'CHANTYPE', 'GROUPING', 'DETCHANS', 'CORRSCAL', 'CORRFILE', 'RESPFILE', 'ANCRFILE', 'BACKFILE', 'RFLORDER', 'DATE_OBS', 'DATE_END', 'EXPOSURE', 'LINE_SEP', 'RGSALPHA', 'TCTYP1', 'TCUNI1', 'TCRPX1', 'TCRVL1', 'TCDLT1', 'TLMIN1', 'TLMAX1']
```

Here, the fits file I am using as example. 
[o1spec.zip](https://github.com/linetools/linetools/files/2865601/o1spec.zip)

It seems that the tags are probably different, but this fits file was generated by sas. What should I do to have a file that i can read with linetools? Thanks again

**Comment by profxj** [comment]
I need the keys of the table, e.g.

```
from astropy.table import Table
tab = Table.read('o1spec.fits')
list(tab.keys())
```

**Comment by mc24tu** [comment]
Ah, sorry.
These:
`['CHANNEL', 'COUNTS', 'QUALITY', 'AREASCAL', 'BACKSCAL']
`

**Comment by profxj** [comment]
Ah, ok.  And what are you intended to use for
wavelength/frequency/energy ?   The code
needs something and none of what you have is
in its standard list.
