### ISSUE TITLE
Rebin documentation syntax question

### ISSUE THREAD

**Issue by fcashman** [linetools/linetools#498]
Hi,
I am playing with the rebin task and am not sure what the wavelength array syntax should look like.
I was assuming [starting_wv ending_wv bin_by__num], but I think I am wrong.

Currently, I am able to rebin a spectrum by some arbitrary number, for example, using sp.wavelength[::3].

The code below is working, but I want to know if I can specify a starting wavelength.

>from linetools.spectra.xspectrum1d import XSpectrum1D
>import numpy as np
>sp1 = XSpectrum1D.from_file('44579_totalsp_3col.fits')
>sp2 = sp1.rebin(sp1.wavelength[::3], do_sig=True)
>sp2.write_to_fits('44579_totalsp_3col_rebin_3.fits')

**Comment by ntejos** [comment]
The method will rebin to the new wavelength array given. Thus, if you want to have something starting from `starting_wv` and ending with  `ending_wv` with steps of `wv_steps` you can define `wv_array = np.arange(starting_wv, ending_wv+wv_steps, wv_steps)` and give that to the `.rebin()` method as input. Let us know if this works for you.

**Comment by fcashman** [comment]
Hi,
Thanks so much for the quick reply. Does there need to be a unit specified in the array? I'm getting a new error about units.

Code:
from linetools.spectra.xspectrum1d import XSpectrum1D
import numpy as np
wv_array = np.arange(4316, 5624.1, 0.1)
sp1 = XSpectrum1D.from_file('44579_totalsp_3col.fits')
sp2 = sp1.rebin(wv_array, do_sig=True)
sp2.write_to_fits('44579_totalsp_3col_rebin.fits')

Error:
Traceback (most recent call last):
  File "lt_rebin_single.py", line 5, in <module>
    sp2 = sp1.rebin(wv_array, do_sig=True)
  File "/Users/Cashman/linetools/linetools/spectra/xspectrum1d.py", line 790, in rebin
    new_spec = rebin(self, new_wv, **kwargs)
  File "/Users/Cashman/linetools/linetools/spectra/utils.py", line 284, in rebin
    bwv = np.zeros(nnew + 1) * new_wv.unit
AttributeError: 'numpy.ndarray' object has no attribute 'unit'

**Comment by ntejos** [comment]
Indeed, could you try the same as above but giving units to the `wv_array`? e.g. 
``from astropy import units as u
wv_array = np.arange(4316, 5624.1, 0.1) * u.AA``

**Comment by fcashman** [comment]
Ah, yes. It works perfectly now. THANK YOU.

**Comment by ntejos** [comment]
Great! Closing the issue now. Cheers,
