### ISSUE TITLE
Install under Python 3.6.9

### ISSUE THREAD

**Issue by mifumagalli** [linetools/linetools#507]
Setup file seems unhappy about distutils.config (see below).

This fix seems to work
https://github.com/aplpy/aplpy/commit/fddb0a60551707a0f5eeb3b66924d4d295ade8b2

ERROR: Complete output from command python setup.py egg_info:
ERROR: Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-req-build-_1qlln31/setup.py", line 25, in <module>
conf = config.ConfigParser()
AttributeError: module 'distutils.config' has no attribute 'ConfigParser'

**Comment by profxj** [comment]
If you were using `pip` to install (likely) this must
be because the previous version was too old.

I just put a new one up.  

dev2147

please try it.

**Comment by mifumagalli** [comment]
Thanks - Actually I was installing through github I believe.

Michele Fumagalli
Durham University
michele.fumagalli@durham.ac.uk
www.michelefumagalli.com
astro.dur.ac.uk/image
________________________________

**Comment by profxj** [comment]
Hmm..  Well the fix you suggest is already in `setup.py` on the master branch.
And the trace which shows this call `conf = config.ConfigParser()` 
doesn't match the current `setup.py` either.  

Can you try it again?  Thanks
