### ISSUE TITLE
Consistent naming of variables, methods and functions

### ISSUE THREAD

**Issue by ntejos** [linetools/linetools#56]
I think it will be valuable to define an unique naming convention for common variables for spectra analyses (e.g. flux, flux uncertainty, continuum, wavelength, etc.), methods, functions, etc. This will make the code look easier to interpret and the package easier to develop.

**Comment by nhmc** [comment]
I agree, this would be good.

Does this mean I have to start using `wv` and `fx` instead of `wa` and `fl`? :)

**Comment by ntejos** [comment]
In this regard, should we clean a bit the XSpectrum1D? I see some redundancies like spec.dispersion and spec.wavelength (or are there suppose to be different?).

**Comment by nhmc** [comment]
In specutils.Spectrum1D, the dispersion does not have to be a wavelength (it can be frequency, energy, etc), so we should really use .wavelength instead of .dispersion.

If you would like to make this change in xspectrum1d (and elsewhere), please feel free. Otherwise I will do it at some point.

**Comment by ntejos** [comment]
I think we have somewhat converged to a common notation. Will close this then.
