### ISSUE TITLE
Generate a galaxy line list

### ISSUE THREAD

**Issue by profxj** [linetools/linetools#66]
I am going to begin a galaxy line list, drawing from the CHIANTI
database:  http://www.chiantidatabase.org/

which looks quite fine.

**Comment by nhmc** [comment]
I think this would be a very useful addition.  As far as I know there's no easy-to-use, authoritative galaxy line list, so if we could put one in linetools that would be awesome.

**Comment by moustakas** [comment]
Here's a fairly complete list of the principle optical/near-IR hydrogen and helium recombination lines:
  https://github.com/desihub/desisim/blob/master/data/recombination_lines.dat
For the forbidden (and metal-recombination) lines it's all a matter of degree, i.e., line-strength with respect to H-beta.  I can point you to some key references if you're interested.

**Comment by nhmc** [comment]
Thanks. What's your view of the CHIANTI database?

**Comment by moustakas** [comment]
My last experience using CHIANTI was from a few years ago, so things may have changed. But what I have in my head is that -- for the (nebular/auroral) forbidden lines at least CHIANTI and NIST frequently had discrepancies that I could not reconcile.  However, this was for pretty faint lines, so probably in the noise for a first-pass line-list.

**Comment by profxj** [comment]
I've now used the DESI-preferred lists for emission (from NIST).
And a small list of absorption lines that have a historical (i.e. unknown) origin.
