### ISSUE TITLE
Make a public release

### ISSUE THREAD

**Issue by nhmc** [linetools/linetools#70]
I think we should make a public release of linetools (v0.1?), ideally before the end of the year. What do you think we need to add before this release?  I suggest:

 - Improved documentation, include tutorials for basic usage.
 - The ability to generate Voigt profiles and transitions for LLS/DLAs, ported from xastropy or Barak.

@profxj @ntejos do you have any other suggestions?

**Comment by profxj** [comment]
Those are two key things.  And quite manageable.
If we are ok with the Voigt in xastropy (which used Barak),
I am willing to push that in soon.

Documentation is a bit more onerous but very important.

I might also like to put in an AbsorptionSystem type Class
akin to what I have in xastropy.  But it wouldn’t be necessary.

Shall we have a vid-chat before long to discuss and divide up
the tasks?  Am back in town next week.

Cheers,

X

> On Oct 12, 2015, at 4:56 PM, Neil Crighton <notifications@github.com> wrote:
> 
> I think we should make a public release of linetools (v0.1?), ideally before the end of the year. What do you think we need to add before this release? I suggest:
> 
> Improved documentation, include tutorials for basic usage.
> The ability to generate Voigt profiles and transitions for LLS/DLAs, ported from xastropy or Barak.
> @profxj <https://github.com/profxj> @ntejos <https://github.com/ntejos> do you have any other suggestions?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/linetools/linetools/issues/70>.
> 
> !DSPAM:826,561c48b9854173481918!

----------------------------------------------
J. Xavier Prochaska
UCO/Lick Observatory
1156 High St.
UC Santa Cruz
Santa Cruz, CA 95064

http://www.ucolick.org/~xavier/
http://imps.ucolick.org/
http://www.qpqsurvey.org/
http://k1dm3.ucolick.org/
http://www.ucolick.org/~xavier/IDL/index.html
https://github.com/xastropy/xastropy
https://github.com/linetools/linetools

831-459-2135 (Direct)
831-459-2991 (UCO/Lick Main)
831-459-5244 (Fax)

**Comment by nhmc** [comment]
A chat this week sounds good. Let's coordinate via email.

**Comment by nhmc** [comment]
After discussion we decided to aim for a public release, version 0.1, by the end of the year. We'll try to make these additions before the release (person responsible is in parentheses). They're roughly in order of priority.

 - Update documentation and tutorials (@nhmc, see #49)
 - Add Voigt profile generation code from xastropy (@profxj)
 - Add an emission line list for galaxy spectra. Maybe also absorption lines? (@profxj)
 - Add extra EUV lines to line lists (@profxj, already done?)
 - Make the elements package, http://www.lfd.uci.edu/~gohlke/code/elements.py.html, a dependency, to provide ionization energies and other atomic data. (@nhmc)
 - Add elemental abundances, from e.g. [Asplund et al. 2009](http://adsabs.harvard.edu/abs/2009ARA%26A..47..481A). Refactor existing abundance code. (@profxj, @ntejos)  

If I've forgotten anything, please open a new issue :)

**Comment by ntejos** [comment]
Current abundances scheme is being implemented in (relevant to the latest point):

linetools/lists/linelist.py

defined in:

get_abundance()

and used in:

available_transitions()

**Comment by nhmc** [comment]
Let's set a hard release date for the 27th Jan. The remaining tasks (which I will do) are 

 1. Check readthedocs is building correctly (use new conda functionality is possible)
 2. Finish XSpectrum1D docs and the intro doc page. Clean up other docs where necessary.
 3. Check by hand that all the scripts and GUIs work, since they don't have tests.
 4. Do the actual release (http://docs.astropy.org/en/stable/development/affiliated-packages.html#releasing-an-affiliated-package) 

Let's also try to increase coverage to >80%. It's currently at 55%. @profxj and @ntejos:
if you have the time to write some tests in the next week, that would be great.

**Comment by profxj** [comment]
Sounds good.

Is there any way to do tests on plots (never mind GUIs)?
If not, our goal should be 80% on non-plot methods.

X

> On Jan 12, 2016, at 2:36 PM, Neil Crighton <notifications@github.com> wrote:
> 
> Let's set a hard release date for the 27th Jan. The remaining tasks (which I will do) are
> 
> Check readthedocs is building correctly (use new conda functionality is possible)
> Finish XSpectrum1D docs and the intro doc page. Clean up other docs where necessary.
> Check by hand that all the scripts and GUIs work, since they don't have tests.
> Do the actual release (http://docs.astropy.org/en/stable/development/affiliated-packages.html#releasing-an-affiliated-package <http://docs.astropy.org/en/stable/development/affiliated-packages.html#releasing-an-affiliated-package>)
> Let's also try to increase coverage to >80%. It's currently at 55%. @profxj <https://github.com/profxj> and @ntejos <https://github.com/ntejos>:
> if you have the time to write some tests in the next week, that would be great.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/linetools/linetools/issues/70#issuecomment-171082921>.
> 
> !DSPAM:826,56957ffb13529633730158!

----------------------------------------------
J. Xavier Prochaska
UCO/Lick Observatory
1156 High St.
UC Santa Cruz
Santa Cruz, CA 95064

http://www.ucolick.org/~xavier/
http://imps.ucolick.org/
http://www.qpqsurvey.org/
http://k1dm3.ucolick.org/
http://www.ucolick.org/~xavier/IDL/index.html
https://github.com/pyigm/pyigm
https://github.com/linetools/linetools

831-459-2135 (Direct)
831-459-2991 (UCO/Lick Main)
831-459-5244 (Fax)

**Comment by ntejos** [comment]
Sounds goo to me. It would be better for me if someone assigns me directly
what tests to add, so I can focus on those in a prompter manner.

Cheers,

---Nicolas

**Comment by nhmc** [comment]
@profxj yes, matplotlib and I think also astropy do plot tests. But I won't have time to look at how before the release.

@ntejos I will assign you some tests.

**Comment by profxj** [comment]
@ntejos: Here you go --

1.  spectralline.py
2.  abscomponent.py
3.  elements.py  (this one is hardest; might be that the author has some)

X

**Comment by profxj** [comment]
I'll dig in on the astropy plotting tests.

**Comment by ntejos** [comment]
Sounds good.

**Comment by nhmc** [comment]
Closing. (But we still need to improve test coverage...)
